### get all books:
GET http://localhost:8080/api/books HTTP/1.1
Authorization: Basic sven:1234


### get book with id 1:
GET http://localhost:8080/api/books/1 HTTP/1.1
Authorization: Basic sven:1234

### try to get book with with anvialid id 99999:
GET http://localhost:8080/api/books/99999 HTTP/1.1
Authorization: Basic sven:1234

### get a csrf-token
GET http://localhost:8080/api/books/csrf-token
Authorization: Basic sven 1234


### Add a new book:
POST http://localhost:8080/api/books HTTP/1.1
content-type: application/json
Authorization: Basic sven:1234
X-CSRF-TOKEN: RykPYY-PrCiOQFfOJAJlWWZFXmEELHmYC22GDR8K_0_dRZ9zch0-BL_pzUqjcWX2HS9RbF51cwA9HEi1OVjlP346z3e-J69D

{
    "id" : null,
    "title" : "my added title",
    "verlag" : "new verlag posted",
    "isbn" : "2423-123-12551-123",
    "status" : "LENT",
    "student" : null
}


### Add a new book without status and id:
POST http://localhost:8080/api/books HTTP/1.1
content-type: application/json
Authorization: Basic sven:1234
X-CSRF-TOKEN: cFoYubnlrqxbNSg4fpGz5oHNHP1mlw5byFC3Lmz4TndGCSc5Qjh82oiGmp92UU1cSryH1uOrMcVXpzh2q2LUFlTJLUAkOkZY

{
    "title" : "title without status, id",
    "verlag" : "new verlag posted",
    "isbn" : "2423-123-12551-123",
    "student" : null
}


### Add invalid new book without title:
POST http://localhost:8080/api/books HTTP/1.1
content-type: application/json

{
    "title" : "",
    "verlag" : "new verlag posted",
    "isbn" : "2423-123-12551-123",
    "student" : null
}


### Add a new book without status and student_id:
POST http://localhost:8080/api/books HTTP/1.1
content-type: application/json

{
    "title" : "title without status, student_id",
    "verlag" : "new verlag posted",
    "isbn" : "2423-123-12551-123"
}

### Add a second book with different status
POST http://localhost:8080/api/books HTTP/1.1
content-type: application/json

{
    "id": null,
    "title": "Lighthouse English 8",
    "isbn": "73649-8632-97942-9",
    "verlag": "klett",
    "status": "MISSING",
    "student": null
}

### should update book with id 1
PUT http://localhost:8080/api/books/1 HTTP/1.1
Content-Type: application/json

{
    "id" : "1",
    "title" : "new title",
    "verlag" : "new verlag",
    "isbn" : "2423-123-12551-123",
    "status" : "LENT",
    "student" : null
}

### should not update book because of wrong status
PUT http://localhost:8080/api/books/1 HTTP/1.1
Content-Type: application/json

{
    "id" : "1",
    "title" : "wrong status",
    "verlag" : "new verlag",
    "isbn" : "2423-123-12551-123",
    "status" : "NotAStatus",
    "student" : null
}

### should not update book, because of invalid id
PUT http://localhost:8080/api/books/999 HTTP/1.1
Content-Type: application/json

{
    "id" : "999",
    "title" : "new title",
    "verlag" : "new verlag",
    "isbn" : "2423-123-12551-123",
    "status" : "LENT",
    "student" : null
}

###DELETE
### should deletebook
DELETE  http://localhost:8080/api/books/1 HTTP/1.1


### should throw BookNotFoundException on deletebook
DELETE  http://localhost:8080/api/books/9999 HTTP/1.1
