### Add a new book:
POST http://localhost:8080/api/book HTTP/1.1
content-type: application/json

{
    "id": null,
    "title": "My first Test Book",
    "author": "The best author",
    "status": "AVAILABLE",
    "student": null
}

### Add a second book with different status
POST http://localhost:8080/api/book HTTP/1.1
content-type: application/json

{
    "id": null,
    "title": "Lighthouse English 8",
    "isbn": "73649-8632-97942-9",
    "verlag": "klett",
    "status": "MISSING",
    "student": null
}