### Add a new book:
POST http://localhost:8080/api/book HTTP/1.1
content-type: application/json

{
    "id" : null,
    "title" : "my added title",
    "verlag" : "new verlag posted",
    "isbn" : "2423-123-12551-123",
    "status" : "LENT",
    "student" : null
}

### Add a second book with different status
POST http://localhost:8080/api/book HTTP/1.1
content-type: application/json

{
    "id": null,
    "title": "Lighthouse English 8",
    "isbn": "73649-8632-97942-9",
    "verlag": "klett",
    "status": "MISSING",
    "student": null
}

###
PUT http://localhost:8080/api/book/1 HTTP/1.1
Content-Type: application/json

{
    "id" : "1",
    "title" : "new title",
    "verlag" : "new verlag",
    "isbn" : "2423-123-12551-123",
    "status" : "LENT",
    "student" : null
}